### ISSUE TITLE
FreeRTOS Watchdog Alerts

### ISSUE THREAD

**Issue by greg80303** [aliengreen/esp32_uart_bridge#1]
When I build and flash this firmware to my ESP32, I see this message repeated in the serial console:

```
E (85266) task_wdt: Task watchdog got triggered. The following tasks/users did not reset the watchdog in time:
E (85266) task_wdt:  - IDLE (CPU 0)
E (85266) task_wdt: Tasks currently running:
E (85266) task_wdt: CPU 0: uart_bridge_tas
E (85266) task_wdt: Print CPU 0 (current core) registers
Core  0 register dump:
MEPC    : 0x40384ed6  RA      : 0x4200ab10  SP      : 0x3fc91ad0  GP      : 0x3fc8c600  
TP      : 0x3fc88e0c  T0      : 0x4038a8e4  T1      : 0x0000000f  T2      : 0x00000000  
S0/FP   : 0x3fc9281c  S1      : 0x00000000  A0      : 0x3fc91d14  A1      : 0x3fc91adc  
A2      : 0x00000000  A3      : 0x00000200  A4      : 0x3fc8e000  A5      : 0x3fc91cbc  
A6      : 0x00000001  A7      : 0x00000000  S2      : 0x00000000  S3      : 0x00000000  
S4      : 0x00000000  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x00000000  T4      : 0x00000000  T5      : 0x00000000  T6      : 0x00000000  
MSTATUS : 0x00000000  MTVEC   : 0x00000000  MCAUSE  : 0x00000000  MTVAL   : 0x00000000  
MHARTID : 0x00000000  
```

and then my ESP32-C3 reboots.  Anyone have ideas as to why I'm seeing this?

**Comment by lashad** [comment]
Which version of ESP-IDF are you using to build?

**Comment by greg80303** [comment]
`ESP-IDF v5.0.2-dirty`

Not sure what the "dirty" means.

**Comment by lashad** [comment]
I've not tested on 5.0.2-dirty.

But, try disable watchdog timer from `idf.py menuconfig`  
Uncheck `Enable Task Watchdog Timer` from → Component config → ESP System Settings

and rebuild project

**Comment by greg80303** [comment]
OK -- I will try that.  I also just did a fresh install of ESP-IDF from github and I'm seeing the same thing
```
> idf.py --version
ESP-IDF v5.3-dev-262-g294c2bd70d-dirty
```

**Comment by greg80303** [comment]
I created a PR (#2) to fix the watchdog timer.  The previous code had 0 timeouts for the read/write calls which essentially created a spin-loop, starving the other FreeRTOS threads/tasks.

However, I'm still having a problem getting the bridge to work.  When I connect my serial terminal to the ESP32 via USB, I'm still only seeing the console for the ESP32 itself (which is where I noticed the watchdog timer warnings), not my attached MCU.

I have these values in my `sdkconfig`:
```
CONFIG_ESP_CONSOLE_UART_DEFAULT=y
CONFIG_ESP_CONSOLE_SECONDARY_USB_SERIAL_JTAG=y
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED=y
CONFIG_ESP_CONSOLE_UART=y
CONFIG_ESP_CONSOLE_UART_NUM=0
CONFIG_ESP_CONSOLE_UART_BAUDRATE=115200

CONFIG_UBRIDGE_UART_PORT_NUM=1
CONFIG_UBRIDGE_UART_BAUD_RATE=115200
CONFIG_UBRIDGE_UART_PARITY_NONE=y
CONFIG_UBRIDGE_UART_PARITY=0
CONFIG_UBRIDGE_UART_RXD=5
CONFIG_UBRIDGE_UART_TXD=4
```

I think `CONFIG_ESP_CONSOLE_UART_NUM=0` means that the ESP32 console logs are using UART port 0, while `CONFIG_UBRIDGE_UART_PORT_NUM=1` means that my MCU should be using UART port 1.  But when I connect my external computer to the ESP32 with a USB cable, should that cable be connected to the USB port on the ESP32C3?  Or am I supposed to be using a USB cable with duponts on one end and connecting it to some other pins on the ESP32C3?  The main USB port on the ESP32 seems to only be providing ESP32 console logs (UART port 0).

**Comment by lashad** [comment]
That's right, 
ESP32C3 console output should be on port number 0, as exactly what you have in your config `CONFIG_ESP_CONSOLE_UART_NUM=0` and Bridge number should be 1

Make sure your computer is linked to the internal USB of the ESP32C3 via the dedicated pins `GPIO18` for USB D- and `GPIO19` for USB D+. It's important - these pins are fixed and cannot be reassigned to different pins. Verify your board to confirm whether the USB connection is directly internal or if there's an intermediary converter chip handling the connection between USB and the ESP32C3.
For communication with secondary MCUs, make sure to connect `GPIO5` to RX and `GPIO4` to TX. These pins should be linked to the corresponding RX->TX and TX->RX of the secondary MCUs, respectively.
If you observe console outputs on your computer's USB port, it indicates a potential issue with the connections.

I Suggest:
- Before proceeding, make sure to update the code. I've made some modifications to the WDT, although they are not directly related to the current issue. it's advisable to have the latest code version.
- Check `GPIO18` for USB D- and `GPIO19` for USB D+. It's important
- Set CONFIG_ESP_CONSOLE_UART_DEFAULT to 'n' to disable console output. Since the code operates in bridge mode, there's no need for any information to be printed.

BTW which ESP32C3 module are you using?

**Comment by greg80303** [comment]
I'm using the Espressif ESP32-C3-DevKitM-1.  It has a micro-usb connector on it -- but I'm not sure how it is connected to GPIO18/19 internally.  Let me see if I can research that a bit

I'll update the code and try the couple of suggestions you've made.  Thanks again for your responses.

**Comment by lashad** [comment]
Ah, Ok

Certainly, I understand the issue. The ESP32-C3-DevKitM-1 comes equipped with an internal USB-UART bridge IC, as previously mentioned. Your USB cable is internally connected to GPIO21 (U0TXD) and GPIO20 (U0RXD), leading to the observed console outputs on your computer terminal.

However, the firmware is designed for an internal USB JTAG-to-bridge configuration on the UART port of the ESP32C3. The primary concept involves connecting the host computer to a secondary MCU, such as an STM32 or a similar one with a UART interface, through the ESP32C3. In this setup, the ESP32C3 act as CP21xx or FTD IC chip.

Given that your DevKit module already includes a CP21xx on the board, using this firmware becomes unnecessary. A more effective approach is to directly connect your secondary MCU to GPIO21 (U0TXD) and GPIO20 (U0RXD) pins. The recommended configuration is as follows:

| ESP32C3    |   Other MCU |
| -------------|--------------|
| GPIO21(TX) |      RX              |
| GPIO20(RX) |      TX             |

Subsequently, connect your host computer to USB and operate without the ESP32C3, as you can communicate with the secondary MCU through the internal CP21xx.
